### ISSUE TITLE
Integrating cosmos provider for XDEFI

### ISSUE THREAD

**Issue by loxator** [delphi-labs/shuttle#100]
Hi there!

I am a developer from  XDEFI Wallet, I would like to add our cosmos provider to this library. I see that you already have one for Terra (thanks btw!). 

I cloned the repo and trying to run `npm build` but it gives all sorts of typescript errors. I have added `//@ts-nocheck` for now to generate a build and then linking the package. However, I am not sure if the build is ok, as using the linked package throws all sorts of issues.

Could you help me get started with this and any pointers to get this integrated? Thanks!

**Comment by afsardo** [comment]
Yes let me take a look!

**Comment by afsardo** [comment]
Merged.
