### ISSUE TITLE
On Mobile - Leap always redirects to play store

### ISSUE THREAD

**Issue by thandaanda** [delphi-labs/shuttle#134]
Hi Team,

When attempting to connect the Leap Wallet with Shuttle on mobile devices, instead of opening Leap, the link consistently redirects to the Play Store, even though Leap is already installed.

**Comment by afsardo** [comment]
We are currently working on WalletConnect v2 so for now mobile wallet experiences are affected a bit.

**Comment by afsardo** [comment]
@thandaanda it should be fixed now with this [commit](https://github.com/delphi-labs/shuttle/commit/c1f7b005d61192827505604c43846dd5b4aa055f).
