### ISSUE TITLE
Lost connection with the Kelpr wallet and Leap wallet

### ISSUE THREAD

**Issue by vuadenthuj1** [delphi-labs/shuttle#140]
After connecting to the wallet by Dapp, I refreshed the browser and lost the connection. The key shuttle has been deleted from the local storage

**Comment by afsardo** [comment]
Hum this is an interesting issue, is there any way you can share a bit more on the issue?

**Comment by afsardo** [comment]
@vuadenthuj1 any more information on this?

**Comment by afsardo** [comment]
Once you have more details about this issue let us know and feel free to re open it.
