### ISSUE TITLE
signArbitrary() with Injective gives 'Error: Unsupported algorithm: ethsecp256k1'

### ISSUE THREAD

**Issue by AKnownEntity** [delphi-labs/shuttle#162]
I'm trying to use Shuttle to sign an arbitrary message and prove ownership on the injective network.

I will skip most of the setup, but the code I am using for signing a network comes from the react example:

```
    const data = "123"
    const bytes = Buffer.from(data, "utf-8");

    signArbitrary({
      wallet,
      data: bytes,
    })
      .then(async (result) => {
        console.log("sign arbitrary result", result);

        console.group("###### verifying signature.... ########");
        const verification = await verifyArbitrary({
          wallet,
          data: bytes,
          signResult: result,
        });
        console.log("verification result:", verification);
        console.log("####################################");
        
        console.groupEnd();
      })
      .catch((error) => {
        console.error("sign arbitrary error", error);
      });
```

When I run this, I always get a console error after signing the tx: `sign arbitrary error Error: Unsupported algorithm: ethsecp256k1`
I am using a  Keplr wallet for this test.

Any help with this issue? Am I missing something?

**Comment by afsardo** [comment]
Yeah unfortunately Keplr doesn't support injective for signArbitrary.

**Comment by thandaanda** [comment]
@afsardo 
Does this solve the issue - https://github.com/chainapsis/keplr-wallet/pull/694

**Comment by afsardo** [comment]
That should be it! Will take a look by EOW, thanks for the link

**Comment by afsardo** [comment]
@thandaanda From what I understood, I don't think we need to do anything in Shuttle right? This should start working as soon as that fix is out with a new Keplr version?

**Comment by thandaanda** [comment]
@afsardo We were able to fix verifyArbitray using `verifyADR36Amino` from `@keplr-wallet/cosmos`. However, we have ran into issues for mobile providers.
We tried with Leap, Keplr and Metamask mobile.

Demo - https://shuttle.keyval.me/
Repo - https://github.com/thandaanda/nextjs-shuttle-demo

**Comment by afsardo** [comment]
> @afsardo We were able to fix verifyArbitray using `verifyADR36Amino` from `@keplr-wallet/cosmos` for extensions. However, we have ran into issues for mobile providers. We tried with Leap, Keplr. Metamask works with provided values.
> 
> When we contacted Leap team, they said walletconnect is not supported so using Leap Browser is a way to go.
> 
> For Keplr, we changed the data to sign - https://github.com/thandaanda/nextjs-shuttle-demo/blob/main/src/components/ArbitrarySign.tsx#L77
> 
> Do you think there is a bug in the `prepareSigningWithMemo` code since it doesn't send any message.
> 
> Demo - https://shuttle.keyval.me/ Repo - https://github.com/thandaanda/nextjs-shuttle-demo

Will have to give it a run, and check out.

**Comment by thandaanda** [comment]
@afsardo We can close this ticket. We created custom signArbitry call for mobile providers.
