### ISSUE TITLE
What is the difference between shuttle and WalletConnect

### ISSUE THREAD

**Issue by nanjiangwill** [delphi-labs/shuttle#2]
I think WalletConnect also support cosmos wallet

what is the unique value offering of shuttle?

**Comment by afsardo** [comment]
Hi @nanjiangwill, WalletConnect hopefully in the future will be able to replace this package indeed.

But it's still not quite ready for Cosmos usage yet, at least the way I understand it currently.

---

The unique value prop of Shuttle, even comparing to similar solutions is a more abstract way to interact to wallet extensions. Most packages focus on giving you the direct interface to them, on a more low level access, something that Terra.js offered was, it abstracted a lot of the "harder concepts" making it easy for any Frontend Dev to just develop their Dapps and easily connect, send transactions.

What Shuttle aims to do is exactly the same DX but for the broader cosmos chains, making it easy to manage multiple connections of (Wallet, Chain) tuples.

**Comment by afsardo** [comment]
A major feature Shuttle offers compared to all others is the integration with TerraStation.
